# ??????????8080?
server:
  port: 8080

# ???MQTT??????iot.mqtt??MqttProperties?prefix???
iot:
  mqtt:
    broker: tcp://127.0.0.1:1883 # MQTT????
    clientId: my-iot-client-001 # ??????ID
    username: admin # MQTT????????MQTT????????
    password: 123456 # MQTT???????MQTT????????
    connectTimeout: 60 # ??????60?
    keepAliveInterval: 30 # ????30?